services:
  recon:
    build:
      context: .                      #look in this directory
      dockerfile: Dockerfile          #repo dockerfile name
    container_name: script
    networks:
      - recon
    stdin_open: true                  #equivalent to docker run -i
    tty: true                         #equivalent to docker run -t
  
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"                   #expose localhost:3000
    networks:
      - recon
    logging:              
      driver: "none"                  #ignore terminal stdout for juice-shop

networks:
      recon-net:
        driver: bridge