services:
  recon:
    build:
      context: .                      #look in this directory
      dockerfile: Dockerfile          #repo dockerfile name
    container_name: script
    networks:
      - recon
    stdin_open: true                  #equivalent to docker run -i
    tty: true                         #equivalent to docker run -t
    volumes:
      - .:/app                        #mounts docker workdir to host current dir, intended for accessing file outputs
    command: tail -f /dev/null

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"                   #expose localhost:3000
    networks:
      recon:
        aliases:
          - juice-shop.local        #gospider has some strict domain parsing rules!!

networks:
  recon:
    driver: bridge